<a href="https://colab.research.google.com/github/rabiyulfahimhasim786/ystocks-data/blob/main/yahoogainers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import bs4
from bs4 import BeautifulSoup
import requests
import csv
import pandas as pd

In [21]:
symbols=[]
names=[]
prices=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
#for i in range(0,11):
url = "https://finance.yahoo.com/most-active?offset=0&count=100"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'}
r= requests.get(url, headers=headers)
data=r.text
soup=BeautifulSoup(data)
 
for listing in soup.find_all('tr', attrs={'class':'simpTblRow'}):
  for symbol in listing.find_all('td', attrs={'aria-label': 'Symbol'}):
    symbols.append(symbol.text)
  for name in listing.find_all('td', attrs={'aria-label':'Name'}):
    names.append(name.text)
  for price in listing.find_all('td', attrs={'aria-label':'Price (Intraday)'}):
    prices.append(price.text)
  for change in listing.find_all('td', attrs={'aria-label':'Change'}):
    changes.append(change.find('span').text)
  for percentChange in listing.find_all('td', attrs={'aria-label':'% Change'}):
    percentChanges.append(percentChange.find('span').text)
  for totalVolume in listing.find_all('td', attrs={'aria-label':'Avg Vol (3 month)'}):
    totalVolumes.append(totalVolume.text)
  for circulatingSupply in listing.find_all('td', attrs={'aria-label':'Volume'}):
    circulatingSupplys.append(circulatingSupply.text)
  for marketCap in listing.find_all('td', attrs={'aria-label':'Market Cap'}):
    marketCaps.append(marketCap.text)
 
dataframe = pd.DataFrame({"Symbols": symbols, "Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges, "Volume": circulatingSupplys, "Average Volume": totalVolumes, "Market Cap": marketCaps,})#"Volume":circulatingSupplys})

In [23]:
dataframe.to_csv('demo.csv')

In [24]:
dataframe

,Symbols,Names,Prices,Change,% Change,Volume,Average Volume,Market Cap
0,AMD,"Advanced Micro Devices, Inc.",85.45,+2.67,+3.23%,68.937M,82.866M,137.944B
1,AAPL,Apple Inc.,157.37,+2.91,+1.88%,68.081M,73.907M,2.529T
2,F,Ford Motor Company,15.42,-0.05,-0.32%,60.964M,62.49M,61.992B
3,T,AT&T Inc.,17.03,+0.26,+1.55%,53.52M,39.035M,121.356B
4,NIO,NIO Inc.,19.16,+1.48,+8.37%,54.144M,49.484M,32.052B
...,...,...,...,...,...,...,...,...
95,FTI,TechnipFMC plc,9.04,+0.42,+4.87%,11.307M,8.041M,4.088B
96,ZS,"Zscaler, Inc.",188.00,+33.75,+21.88%,11.398M,2.193M,26.67B
97,DAL,"Delta Air Lines, Inc.",32.66,+0.54,+1.68%,10.764M,12.311M,20.942B
98,MRVL,"Marvell Technology, Inc.",49.74,+1.59,+3.30%,10.92M,9.992M,42.274B
99,BABA,Alibaba Group Holding Limited,92.14,+2.62,+2.93%,10.553M,23.582M,244.654B

In [ ]:
# References - https://hackernoon.com/scraping-yahoo-finance-data-using-python-ayu3zyl